### ISSUE TITLE
Incorrect target type for RelativeAncestor attached properties

### ISSUE THREAD

**Issue by Sergio0694** [CommunityToolkit/Windows#106]
## Describe the bug

The attached properties for the "relative ancestor" feature are currently targeting the wrong type:

https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/44ad0cc6806c99f1a693c923cb94ea7551718c13/Microsoft.Toolkit.Uwp.UI/Extensions/FrameworkElement/FrameworkElementExtensions.RelativeAncestor.cs#L18-L21

These are defined in `FrameworkElementExtensions` but target a `DependencyObject`. This is not correct on its own, but in particular it also makes the APIs technically more error prone, as there is no type guarantee at build-time, and we're doing additional checks at runtime to ensure the input elements are in fact `FrameworkElement`-s, otherwise we do nothing:

https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/44ad0cc6806c99f1a693c923cb94ea7551718c13/Microsoft.Toolkit.Uwp.UI/Extensions/FrameworkElement/FrameworkElementExtensions.RelativeAncestor.cs#L62-L65

Given that these APIs only make sense for `FrameworkElement` instances, and that they're defined within `FrameworkElementExtensions` too, we should update the signature and have them only target `FrameworkElement` objects. I should note: this would not be a source breaking change when the API was being used correctly, but it would be a binary breaking change.

**Comment by michael-hawker** [comment]
Thanks @Sergio0694, brought this over to the new repo and will fix in #105.

Note, `Ancestor` can be a `DependencyObject` still as it's the output of the call to `FindAscendant` which can return a `DependencyObject`.

However, you're correct, since we generally want to wait until the element is loaded, we should make `AncestorType` dependent on `FrameworkElement`. Related to our discussion in Labs too: https://github.com/CommunityToolkit/Labs-Windows/discussions/449

Though technically, we could still call the visual tree helpers on a DependencyObject, I don't think there's going to be many of those cases though, so think fine to exclude?
