### ISSUE TITLE
Uniform Grid - Rendering issue

### ISSUE THREAD

**Issue by Gavin-Williams** [CommunityToolkit/Windows#558]
### Describe the bug

I have a uniform grid with images and solid borders (acting as background color) in each cell. The images in the first cell seem to be rendered out of order. 

If I don't explicitly set z-order they are simply reversed from the order they were added. So, I can have either all image rendered but with 1 image missing in cell 0,0 or I can have all borders rendered in front with 1 image rendered in cell 0,0.

If I explicitly set z-order, the same behavior occurs with regard to images added second - that is, the image in cell 0,0 is not rendered (or rendered behind the border). If I switch the order of adding elements - the images are rendered correctly, respecting z-order and images are in front of border in each cell.

### Steps to reproduce

Here's a one-drive share of a test project showing the issue...

[Sample project](https://1drv.ms/u/s!AhbcRtciy6_0ma5kDH6CyGrvgVjwGQ?e=mUCzHA)
### Expected behavior

Firstly, the images should be rendered in front of the borders because they are added second. And secondly, the images should be rendered in front of the borders because of the explicit z-order assignments.

### Screenshots

![Image](https://github.com/user-attachments/assets/88ac3efb-dcdb-4d0e-8309-febe663d9c87)

### Code Platform

- [ ] UWP
- [x] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [x] Other (specify)

### Other Windows Build number

26100.2314

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [x] Other (specify)

### Other SDK version

10.0.22621.0

### Visual Studio Version

2022

### Visual Studio Build Number

17.12.0

### Device form factor

Desktop

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by Gavin-Williams** [comment]
I checked Grids behavior - it works correctly.

**Comment by Gavin-Williams** [comment]
@michael-hawker I don't understand that note, or how it's relevant to me. Except to say that I guess this is relevant...
> in order to pin a child to the top-left position (0, 0)
Beyond that, I can't make any sense of the note. I'm using the UGrid the way that I would use the Grid AFAICT. If I'm 'overwriting the location of every cell' and 'overwriting the default behavior of the control' - well, that's news to me. I feel like I'm using it the way it's meant to be used, that is, I've set their row and columns and added them to the UGrid.

I have no knowledge of the AutoLayout system and I don't understand the edge case they are talking about. Sorry.

**Comment by Gavin-Williams** [comment]
So this seems to work...

```

**Comment by michael-hawker** [comment]
@Gavin-Williams this panel isn't normally used to specify every specific location of its contents, normally you provide it a bunch of children like you would a `StackPanel` and it will automatically lay them out in the grid.

i.e. if you add each of your square cell containers in order from left-to-right, top-to-bottom and just set `Columns` to 8, you'll automatically have your chessboard.

Yes, this is a `Grid` technically, but that's an additional feature to allow for advanced scenarios (e.g. having all the elements flow around one you pin to the middle). As from its WPF roots, it's meant to panel to be used as part of an ItemsControl/ListView container that lets you freeflow content in a grid structure. Its original usage was for laying out a Calendar for instance.

I'd suggest for your use case that you use a DataTemplate or a UserControl container so that each cell is a single entity and the `UniformGrid` just handles scaling to the window size vs. continually adding/removing items from within it.

I hope this context helps. Thanks!
